import pickle
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request
from googleapiclient.http import MediaFileUpload
import os
import json
import asyncio
import requests
import edge_tts
from google import genai
from google.genai import types

# --- 1. SETUP ---
os.environ["GEMINI_API_KEY"] = "AQ.Ab8RN6LYk6MMnX00pyAX2MzjaSkFS6z38yxxyRPVlS0MTSj_Kg"
PEXELS_API_KEY = "o6Xl4STjlFnpUwbvINQNf3Rpq2xt0BmypFXrO7etUhZzSYKbUsWQ8Ddf"

VOICE = "en-US-ChristopherNeural"
OUTPUT_AUDIO = "voiceover.mp3"

# --- 2. THE BRAIN (GEMINI) ---
def generate_script():
    print("🧠 Asking Gemini to write the script...")
    client = genai.Client()
    prompt = """
    Write a 45-second YouTube Short script about a fascinating space phenomenon.
    Format your response as a JSON object with two keys:
    - "script": The spoken text of the video.
    - "image_prompts": A list of 5 short visual descriptions (max 5 words each) matching the script.
    """
    response = client.models.generate_content(
        model='gemini-2.5-flash',
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            temperature=0.7
        )
    )
    return json.loads(response.text)

# --- 3. THE VOICE (EDGE-TTS) ---
async def generate_audio(text):
    print(f"🎙️ Generating voiceover ({VOICE})...")
    communicate = edge_tts.Communicate(text, VOICE)
    await communicate.save(OUTPUT_AUDIO)
    print(f"✅ Success! Audio saved as {OUTPUT_AUDIO}")

# --- 4. THE VISUALS (PEXELS API) ---
def download_videos(prompts):
    print("\n🎬 Searching and downloading videos from Pexels...")
    headers = {"Authorization": PEXELS_API_KEY}
    
    # Create a folder to store downloaded videos
    if not os.path.exists("videos"):
        os.makedirs("videos")

    for index, prompt in enumerate(prompts):
        print(f"🔍 Searching for: {prompt}")
        # We tell Pexels we only want 'portrait' (vertical) videos for YouTube Shorts
        url = f"https://api.pexels.com/videos/search?query={prompt}&orientation=portrait&per_page=1"
        response = requests.get(url, headers=headers)
        
        if response.status_code == 200:
            data = response.json()
            if len(data["videos"]) > 0:
                # Grab the actual direct .mp4 download link
                video_url = data["videos"][0]["video_files"][0]["link"]
                print(f"⬇️ Downloading video {index + 1}...")
                
                # Download and save the .mp4 file
                vid_data = requests.get(video_url).content
                with open(f"videos/clip_{index}.mp4", "wb") as f:
                    f.write(vid_data)
                print(f"✅ Saved clip_{index}.mp4")
            else:
                print(f"⚠️ No video found for '{prompt}'")
        else:
            print(f"❌ Error connecting to Pexels: {response.status_code}")

# --- 5. MASTER FUNCTION ---
async def main():
    content = generate_script()
    await generate_audio(content["script"])
    download_videos(content["image_prompts"])
    assemble_video()
    
    # NEW: Push it live!
    upload_to_youtube("final_short.mp4", "Fascinating Space Facts #shorts", "An automated video generated by AI.")
    
    print("\n🎉 PHASE 4 COMPLETE! Your factory is running.")

# --- 6. THE DELIVERY GUY (YOUTUBE API) ---
# This tells Google we ONLY want permission to upload videos
SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

def upload_to_youtube(video_file, title, description):
    print("\n🚀 Starting YouTube Upload Process...")
    credentials = None

    # Check if we already logged in before and saved our badge
    if os.path.exists("token.pickle"):
        with open("token.pickle", "rb") as token:
            credentials = pickle.load(token)

    # If no valid badge exists, open the browser so the user can log in
    if not credentials or not credentials.valid:
        if credentials and credentials.expired and credentials.refresh_token:
            credentials.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file("client_secrets.json", SCOPES)
            credentials = flow.run_local_server(port=0)
        
        # Save the badge for tomorrow's automated run
        with open("token.pickle", "wb") as token:
            pickle.dump(credentials, token)

    # Connect securely to YouTube
    youtube = build("youtube", "v3", credentials=credentials)

    # Define the video details
    request_body = {
        "snippet": {
            "categoryId": "22",  # 22 is "People & Blogs"
            "title": title,
            "description": description,
            "tags": ["shorts", "space", "facts", "automation"]
        },
        "status": {
            "privacyStatus": "private",  # Change to "public" once you trust the system!
            "selfDeclaredMadeForKids": False
        }
    }

    # Prepare the file for upload
    media_file = MediaFileUpload(video_file, chunksize=-1, resumable=True)
    
    print("⏳ Uploading to YouTube (this may take a few minutes depending on your internet speed)...")
    
    # Execute the upload
    response = youtube.videos().insert(
        part="snippet,status",
        body=request_body,
        media_body=media_file
    ).execute()

    print(f"✅ Success! Video uploaded to your channel.")
    print(f"🔗 Link: https://youtu.be/{response['id']}")

if __name__ == "__main__":
    asyncio.run(main())