name: YouTube Automation Factory

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch:      # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install and Configure ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          # Overwrite the policy file to allow text rendering for moviepy
          echo '<policymap>
            <policy domain="coder" rights="read|write" pattern="LABEL" />
            <policy domain="coder" rights="read|write" pattern="PDF" />
            <policy domain="path" rights="read|write" pattern="@*" />
          </policymap>' | sudo tee /etc/ImageMagick-6/policy.xml

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth-oauthlib google-auth-httplib2 moviepy==1.0.3 pillow==9.5.0 edge-tts google-generativeai requests

      - name: Create secrets
        run: |
          echo "${{ secrets.CLIENT_SECRETS_BASE64 }}" | base64 --decode > client_secrets.json
          echo "${{ secrets.TOKEN_PICKLE_BASE64 }}" | base64 --decode > token.pickle

      - name: Run Automation Script
        env:
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python generator.py
